---
title: "Gov 50 Final Project"
author: "Eytan Goldstein"
description: "I am interested in exploring data related to comparing voting data in Eastern Europe with GDP per capita. I want to study the correlation between low voting/ low interest in democracy in areas that have struggled to transition from socialism to a capitalistic market system since the fall of the Soviet Union and its satellite states in the 1990s.In essence, I want to study how voting patters across Eastern European states is affected by their economic gains since the introduction of market based economic models. Obviously, this is a broad topic and I will need to find the requisite data sets to follow through with this. Nevertheless, it is a start."
output:
  distill::distill_article:
    self_contained: false
---
Project Proposal:
My research question is how does a coup attempt that has been initiated by military actors affect the chances of the realization of the coup? My hypothesis is that coups that originate with military forces will have higher success rates than coups initiated by other means, such as by rebel forces or by popular revolt. This hypothesis is based on a conception of civil-military relations that dictates the confinement of the military focus to the use of force, while politicians make all decisions for the state. But, should a military be discontent with the actions of the head of state, their previous restrain on entrance into the political sphere could create a decisive shock event that would result in a regime change. Additionally, the military generally holds a monopoly or near monopoly on the deployment of violent means to achieve the objective. The use of violence to affect a successful change of ruler is another reason that a military led coup may see higher success rates than coups that originate with sectors of society that do not posess the ability to mobilize manpower and violence to achieve regime change. 

My unit of analysis are coups. Specifically, the Cline Center Coup D'Etat data set has 981 coups that occurred between 1945 and 2022. The explanatory variable is coup success. When the "realized" variable is equal to 1, that means the coup has occurred, in that a regime change happened. When the "realized" variable is equal to 0, that indicates that no regime change occurred, even though a coup was initiated. My outcome variable is whether or not the military initiated the coup. With this variable, the Cline Center experts are just looking at conventional militaries, and not security services, spy services, or other kinds of paramilitary formations. When the variable "military" = 1, then the military started the coup. When that variable is set to 0, it originated elsewhere. 

If the average number of successful coups when the military was involved is significantly higher than the average number of successful coups under other conditions such as rebel groups or popular revolt, than I can conclude that there is a positive correlation between military involvement and the probability of a coup's success.


---



